name: 编译openwrt

on:
  watch:
    types: [started]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor == 'dfh1949'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 配置环境
      run: |
        sudo apt-get update -y
        sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
              bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
              g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
              libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev \
              libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
              ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
              python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
              upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd

    - name: Clone immortalwrt
      run: |
        git clone  https://github.com/immortalwrt/immortalwrt.git
        cd imm

    - name: 更新安装feed
      run: |
        cd imm
        ./scripts/feeds update -a
        ./scripts/feeds install -a
      
    - name: 恢复配置文件
      run: |
        cd imm
        # 生成默认配置，确保基于目标设备
        make defconfig
        # 应用 diffconfig（包选择等）
        if [ -f ../diffconfig ]; then
           cat ../diffconfig >> .config
           make defconfig  # 再次展开，确保依赖完整
        fi

    - name: 自定义配置
      run: |
        cd imm
        # 复制自定义 files 目录（包含 network 配置）
        if [ -d ../files ]; then
          cp -r ../files .
        fi


    - name: 更改内核配置
      run: |
        cd imm
        # 生成默认配置，确保基于目标设备
        make defconfig
        # 应用 diffconfig（包选择等）
        if [ -f ../config-6.12 ]; then
           cat ../kconfig >> target/linux/rockchip/armv8/config-6.12
        fi
  
    - name: 下载依赖
      run: |
        cd imm
        make download -j$(nproc) V=s

    - name: 编译
      run: |
        cd imm
        make -j$(nproc) V=s

    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-firmware
        path: imm/bin/targets/rockchip/armv8/*.img.gz
        retention-days: 30
