name: 编译immortalwrt

on:
  watch:
    types: [started]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 新增：job 总超时 6 小时，防长时构建卡死
    if: github.actor == 'dfh1949'

    steps:
    - name: 检出仓库
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: 检查空间
      if: (!cancelled())
      run: df -hT

    - name: 释放空间
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: 再次检查空间
      if: (!cancelled())
      run: df -hT

    - name: 安装依赖
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
          g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
          libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev \
          libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
          ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
          python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
          upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
          
    - name: 缓存
      uses: actions/cache@v4
      with:
        path: |
          openwrt/dl/
          ~/.ccache/
        key: ${{ runner.os }}-openwrt-feeds-${{ hashFiles('openwrt/feeds.conf.default') }}
        restore-keys: |
          ${{ runner.os }}-openwrt-feeds-

    - name: Clone OpenWrt source  # 修改：硬编码 master，优化 git 重置
      run: |
        if [ -d openwrt ]; then
          echo "openwrt 目录已存在（缓存恢复），尝试更新..."
          cd openwrt
          # 重置 git 状态，清理可能的坏 HEAD
          git reset --hard
          git clean -fd
          git fetch origin --depth=1 master || {
            echo "fetch 失败，清理并重新克隆..."
            cd .. && rm -rf openwrt
            git clone --depth=1 --branch master https://github.com/immortalwrt/immortalwrt.git openwrt
            cd openwrt
          }
          git checkout master --force
          git pull origin master --ff-only --depth=1 || {
            echo "pull 失败，清理并重新克隆..."
            cd .. && rm -rf openwrt
            git clone --depth=1 --branch master https://github.com/immortalwrt/immortalwrt.git openwrt
            cd openwrt
          }
          echo "更新完成"
        else
          echo "openwrt 目录不存在，进行克隆..."
          git clone --depth=1 --branch master https://github.com/immortalwrt/immortalwrt.git openwrt
          cd openwrt
        fi
        # 验证当前分支
        echo "当前分支: $(git rev-parse --abbrev-ref HEAD)"

    - name: 更新安装feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: 复制配置文件
      run: |
        cd openwrt
        # 生成默认配置，确保基于目标设备
        make defconfig
        # 应用 diffconfig（包选择等）
        if [ -f ../diffconfig ]; then
          echo "配置文件存在"
          cat ../diffconfig >> .config
          make defconfig  # 再次展开，确保依赖完整
        fi

    - name: 复制内核文件
      run: |
        cd openwrt
        # 替换为你的 target
        if [ -f ../kconfig ]; then
          echo "内核文件存在"
          cp ../kconfig target/linux/rockchip/armv8/config-6.12
        fi
        # 验证 kernel config 是否应用（非交互式）
        if [ -f target/linux/rockchip/armv8/config-6.12 ]; then
          echo "文件存在"
          head -n 10 target/linux/rockchip/armv8/config-6.12
        fi

    - name: 自定义配置文件
      run: |
        cd openwrt
        # 复制自定义 files 目录（包含网络配置）
        if [ -d ../files ]; then
          echo "文件存在"
          cp -r ../files .
        fi
        # 验证 network config 是否应用
        if [ -f files/etc/config/network ]; then
          echo "文件覆盖"
          cat files/etc/config/network
        fi

    - name: 下载依赖
      timeout-minutes: 60  # 新增：步骤超时 1 小时，防单文件卡死
      run: |
        cd openwrt
        # 新增：设置 wget 参数，重试机制解决连接失败
        export WGET_FLAGS="--tries=3 --timeout=30 --retry-connrefused --waitretry=5 --read-timeout=30"
        # 分离下载和 prepare，先下载（带 V=s 看日志），失败重试一次
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: 编译
      timeout-minutes: 180  # 新增：编译步骤超时 3 小时
      run: |
        cd openwrt
        make -j$(nproc) V=s


    - name: 检测是否编译成功
      run: |
        ls openwrt/bin/target/linux/rockchip/armv8

    - name: 上传固件
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-firmware
        path: openwrt/bin/target/linux/rockchip/armv8/*
        retention-days: 30
        
    # 可选步骤：清理工作空间（如果需要）
    - name: 清理工作空间
      if: always() # 无论成功与否都执行
      run: |
        cd openwrt
        make clean # 清理编译生成的文件，但保留下载的源码
