name: 编译immortalwrt

on:
  watch:
    types: [started]
  workflow_dispatch:

jobs:
  OpenWrt_Builder:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    if: github.actor == 'dfh1949'

    steps:
    - name: 检出仓库
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
       
    - name: 检查空间
      run: df -hT

    - name: 释放空间
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: 再次检查空间
      run: df -hT

    - name: 安装依赖
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
          g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
          libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev \
          libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
          ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
          python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
          upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: Clone OpenWrt master
      run: |
        git clone --depth=1 --branch master https://github.com/immortalwrt/immortalwrt.git openwrt
        cd openwrt
        echo "当前分支: $(git rev-parse --abbrev-ref HEAD)"

    - name: 更新安装feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: 检查并应用配置文件
      run: |
        cd openwrt
        echo "=============================="
        if [ -f ../config/diffconfig ]; then
          echo "✅ 已找到 config/defconfig"
          cp ../config/diffconfig .config
          make defconfig
        else
          echo "⚠️ 未找到 config/diffconfig，使用默认配置"
          make defconfig
        fi

        if [ -f ../config/kconfig ]; then
          echo "✅ 已找到 config/kconfig"
          cp ../config/kconfig target/linux/rockchip/armv8/config-6.12
        else
          echo "⚠️ 未找到 config/kconfig，跳过内核配置"
        fi
        echo "=============================="

    - name: 自定义配置文件
      run: |
        cd openwrt
        if [ -d ../files ]; then
          echo "✅ 检测到 files 目录，已复制"
          cp -r ../files .
        fi

    - name: 下载依赖
      timeout-minutes: 60
      run: |
        cd openwrt
        export WGET_FLAGS="--tries=3 --timeout=30 --retry-connrefused --waitretry=5 --read-timeout=30"
        make download -j8
        find dl -size -1024c -exec rm -f {} \;

    - name: 编译
      timeout-minutes: 180
      run: |
        cd openwrt
        make -j$(nproc) V=s

    # 检测是否编译成功
    - name: 检测是否编译成功
      run: |
        ls openwrt/bin/targets/rockchip/armv8
        echo "编译完成"

    # 上传固件
    - name: 上传固件
      uses: actions/upload-artifact@v4
      with:
       name: openwrt-firmware
       path: openwrt/bin/targets/rockchip/armv8/*
       retention-days: 30
